spring.application.name=grocery-ai

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/grocery_ai
spring.datasource.username=harshsharma
spring.datasource.password=grocery@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true